# Generated by Django 4.2.4 on 2023-08-30 19:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import vacancies_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('photo', models.ImageField(null=True, upload_to='managers', verbose_name='Фото')),
                ('job_position', models.CharField(max_length=50, verbose_name='Должность')),
                ('facebook', models.URLField(verbose_name='Ссылка на фейсбук')),
                ('manager_order', models.PositiveIntegerField(default=0)),
                ('contacts', models.ManyToManyField(to='vacancies_app.contact', verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
                'ordering': ['manager_order'],
            },
        ),
        migrations.CreateModel(
            name='MessengerPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название (Viber, Telegram и т.д.)')),
                ('logo', models.FileField(upload_to='', validators=[vacancies_app.models.validate_svg_file], verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Мессенджер',
                'verbose_name_plural': 'Мессенджеры',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка на сайт')),
                ('picture', models.ImageField(upload_to='partners', verbose_name='Логотип')),
                ('partner_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'ordering': ['partner_order'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название Позиции')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('important', models.BooleanField(verbose_name='Отметить как важную')),
                ('picture', models.ImageField(upload_to='positions', verbose_name='Картинка')),
                ('salary', models.CharField(max_length=100, verbose_name='Зарплата')),
                ('location', models.CharField(max_length=100, verbose_name='Город, Страна')),
                ('note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Примечание (если есть)')),
                ('short_description', models.TextField(max_length=300, verbose_name='Краткое описание для мета тега, максимум 300 символов')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('position_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиции',
                'ordering': ['position_order'],
            },
        ),
        migrations.CreateModel(
            name='ManagerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies_app.manager')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies_app.position')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='manager',
            name='positions',
            field=models.ManyToManyField(blank=True, through='vacancies_app.ManagerPosition', to='vacancies_app.position', verbose_name='Позиции'),
        ),
        migrations.AddField(
            model_name='contact',
            name='messenger_platforms',
            field=models.ManyToManyField(to='vacancies_app.messengerplatform', verbose_name='Мессенджеры'),
        ),
    ]
