# Generated by Django 4.2.4 on 2023-08-30 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managerposition',
            options={'ordering': ['order_manager_position'], 'verbose_name': 'Менеджер для позиции', 'verbose_name_plural': 'Менеджеры для позиций'},
        ),
        migrations.RenameField(
            model_name='managerposition',
            old_name='order',
            new_name='order_manager_position',
        ),
    ]
