# Generated by Django 4.2.4 on 2023-08-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messengerplatform',
            name='contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='messenger_platforms',
            field=models.ManyToManyField(to='vacancies_app.messengerplatform'),
        ),
        migrations.AlterField(
            model_name='position',
            name='note',
            field=models.CharField(max_length=100, null=True, verbose_name='Note'),
        ),
    ]
