# Generated by Django 4.2.4 on 2023-08-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_app', '0002_alter_managerposition_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerposition',
            name='order_manager_position',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
