# Generated by Django 4.2.4 on 2023-08-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_app', '0002_remove_messengerplatform_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='hiring_manager',
        ),
        migrations.AddField(
            model_name='hiringmanager',
            name='contacts',
            field=models.ManyToManyField(to='vacancies_app.contact'),
        ),
    ]
