# Generated by Django 4.2.4 on 2023-08-25 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_app', '0003_remove_contact_hiring_manager_hiringmanager_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='important',
            field=models.BooleanField(null=True, verbose_name='Mark as important'),
        ),
        migrations.AlterField(
            model_name='position',
            name='note',
            field=models.CharField(blank=True, max_length=100, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='position',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies_app.currency', verbose_name='Currency'),
        ),
    ]
