# Generated by Django 4.2.4 on 2023-08-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_app', '0003_alter_managerposition_order_manager_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerposition',
            name='order_manager_position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
