# Generated by Django 4.2.4 on 2023-08-25 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_app', '0004_currency_position_important_alter_position_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies_app.currency', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='position',
            name='important',
            field=models.BooleanField(verbose_name='Mark as important'),
        ),
    ]
