# Generated by Django 4.2.4 on 2023-08-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_app', '0005_alter_position_currency_alter_position_important'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('picture', models.ImageField(upload_to='managers')),
                ('contacts', models.ManyToManyField(to='vacancies_app.contact')),
            ],
        ),
        migrations.AlterField(
            model_name='position',
            name='picture',
            field=models.ImageField(upload_to='positions', verbose_name='Picture'),
        ),
        migrations.DeleteModel(
            name='HiringManager',
        ),
        migrations.AddField(
            model_name='manager',
            name='positions',
            field=models.ManyToManyField(to='vacancies_app.position'),
        ),
    ]
