# Generated by Django 4.2.4 on 2023-08-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_app', '0006_manager_alter_position_picture_delete_hiringmanager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='picture',
        ),
        migrations.AddField(
            model_name='manager',
            name='photo',
            field=models.ImageField(null=True, upload_to='managers', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='messenger_platforms',
            field=models.ManyToManyField(to='vacancies_app.messengerplatform', verbose_name='Manager Platforms'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=5, unique=True, verbose_name='Name (UAH, HUF, etc.)'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='contacts',
            field=models.ManyToManyField(to='vacancies_app.contact', verbose_name='Contacts'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='positions',
            field=models.ManyToManyField(to='vacancies_app.position', verbose_name='Positions'),
        ),
        migrations.AlterField(
            model_name='position',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Note'),
        ),
    ]
