# Generated by Django 4.2.4 on 2023-08-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_app', '0008_alter_contact_options_alter_currency_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='salary',
            field=models.CharField(max_length=100, verbose_name='Зарплата в месяц'),
        ),
    ]
