# Generated by Django 4.2.4 on 2023-08-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_app', '0009_alter_position_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='currency',
        ),
        migrations.AlterField(
            model_name='position',
            name='salary',
            field=models.CharField(max_length=100, verbose_name='Зарплата'),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
