# Generated by Django 4.2.4 on 2023-08-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_app', '0010_remove_position_currency_alter_position_salary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['position_order'], 'verbose_name': 'Позиция', 'verbose_name_plural': 'Позиции'},
        ),
        migrations.AddField(
            model_name='position',
            name='position_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
