# Generated by Django 4.2.4 on 2023-08-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_app', '0011_alter_position_options_position_position_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ['manager_order'], 'verbose_name': 'Менеджер', 'verbose_name_plural': 'Менеджеры'},
        ),
        migrations.AddField(
            model_name='manager',
            name='manager_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
