# Generated by Django 4.2.4 on 2023-08-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_app', '0012_alter_manager_options_manager_manager_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='job_position',
            field=models.CharField(default='nem', max_length=50, verbose_name='Должность'),
            preserve_default=False,
        ),
    ]
