# Generated by Django 4.2.4 on 2023-08-26 14:07

from django.db import migrations, models
import vacancies_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_app', '0013_manager_job_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='picture',
            field=models.FileField(upload_to='positions', validators=[vacancies_app.models.validate_svg_file], verbose_name='Картинка'),
        ),
    ]
