# Generated by Django 4.2.4 on 2023-08-26 14:18

from django.db import migrations, models
import vacancies_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_app', '0014_alter_position_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='positions',
            field=models.ManyToManyField(blank=True, to='vacancies_app.position', verbose_name='Позиции'),
        ),
        migrations.AlterField(
            model_name='messengerplatform',
            name='logo',
            field=models.FileField(upload_to='', validators=[vacancies_app.models.validate_svg_file], verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='position',
            name='picture',
            field=models.ImageField(upload_to='positions', verbose_name='Картинка'),
        ),
    ]
