# Generated by Django 4.2.4 on 2023-08-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_app', '0015_alter_manager_positions_alter_messengerplatform_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='short_description',
            field=models.TextField(default='something', max_length=300, verbose_name='Краткое описание для мета тега, максимум 300 символов'),
            preserve_default=False,
        ),
    ]
