# Generated by Django 4.2.4 on 2023-08-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_app', '0016_position_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='facebook',
            field=models.URLField(default='https://facebok.com/', verbose_name='Ссылка на фейсбук'),
            preserve_default=False,
        ),
    ]
