# Generated by Django 4.2.4 on 2023-08-27 22:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_app', '0017_manager_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Description'),
        ),
    ]
