# Generated by Django 4.2.4 on 2023-08-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_app', '0018_alter_position_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка на сайт')),
                ('picture', models.ImageField(upload_to='partners', verbose_name='Логотип')),
                ('partner_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'ordering': ['partner_order'],
            },
        ),
    ]
