version: '3.8'

services:
  echo_work_backend:
    container_name: elitawork-backend-container
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8010:8010"

  echo_elitawork_frontend:
    container_name: elitawork-frontend-container
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/srv/app
    ports:
      - "8011:8011"
