version: '3.8'

services:
  echo_elitawork_backend:
    container_name: elitawork-backend-container
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "127.0.0.1:8010:8010"

  echo_elitawork_frontend:
    container_name: elitawork-frontend-container
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/srv/app
      - /srv/app/node_modules
    ports:
      - "127.0.0.1:8011:8011"